normal:
  username: "MELIKE_GORGUN"
  password: "Alaz060624."

MELIKE_GORGUN:
  username: "MELIKE_GORGUN"
  password: "Alaz060624."

RETAIL_DIRECTOR:
  username: "RETAIL_DIRECTOR"
  password: "rt1221RT!!"

RETAIL_MANAGER:
  username: "RETAIL_MANAGER"
  password: "rt1221RT!!"

RETAIL_SPECIALIST:
  username: "RETAIL_SPECIALIST"
  password: "rt1221RT!!"
